@startuml
title Finite State Machine - updateState()

[*] --> Init

Init --> AvoidCat

AvoidCat --> CheeseToKing : rawCheese > 20
AvoidCat --> AttackEnemy : rawCheese <= 20

AttackEnemy --> AttackCat
attackEnemy --> PlaceTrap

CheeseToKing --> CollectCheese

CollectCheese --> MineDirt : gamePhase > PHASE_START
CollectCheese --> PlaceDirt : gamePhase <= PHASE_START

MineDirt --> PlaceDirt
PlaceDirt --> Explore
Explore --> EndTurn
EndTurn --> Init
AttackCat --> EndTurn

@enduml
