// #########################################################
// !!!!!!!!!! This file is generated by jinja.py !!!!!!!!!!!
// !!!! Dont edit it manually, check in template folder !!!!
// #########################################################

package params_dbe63b76.Communication;

import params_dbe63b76.States.Result;
import battlecode.common.*;
import params_dbe63b76.Robots.Robot;

import static params_dbe63b76.States.Code.CANT;
import static params_dbe63b76.States.Code.OK;

//  Destination: Communication/MessageMicro.java

public class MessageMicro {
    /*
    // We can also encode x/y with relative position
    // With distance max of 8 (16 = -7 / +8) we have 4 bytes
    //
    //                                          30v   24v     16v       8v      0v
    // Messages types (long)                    0b0000_001111111122_222222_33333333; // 30 bits = 1 per squeak, 3 array size
    public static final int TYPE_MICRO        = 0b0111_000000000000_000000_00000000;
    public static final int RELATIVE_POSITION = 0b0000_000000000000_000000_11111111;
    //                                                |  target id |  dir |yyyyxxxx; // Bits 0-7 : 8 bits = log2(16*16)
    public static final int MASK_DIR_TARGET   = 0b0000_000000000000_000111_00000000;
    public static final int MASK_DIR_SENDER   = 0b0000_000000000000_111000_00000000;
    public static final int MASK_TARGET_ID    = 0b0000_111111111111_000000_00000000;
    */

    public static int encodeRelativePosition(MapLocation myLoc, MapLocation targetLoc){
        // x [-8, 7] : 4 bits  -> Encoded as x + 8

        return switch(targetLoc.translate(-myLoc.x, -myLoc.y).hashCode()){
            case 294912 -> 200 ; // Cell (4, 0)
            case -294915 -> 53 ; // Cell (-5, -3)
            case -360447 -> 41 ; // Cell (-6, 1)
            case 360449 -> 217 ; // Cell (5, 1)
            case 98298 -> 146 ; // Cell (1, -6)
            case 32764 -> 132 ; // Cell (0, -4)
            case 163833 -> 161 ; // Cell (2, -7)
            case -491528 -> 0 ; // Cell (-8, -8)
            case -163834 -> 94 ; // Cell (-3, 6)
            case 32773 -> 141 ; // Cell (0, 5)
            case 163842 -> 170 ; // Cell (2, 2)
            case -491519 -> 9 ; // Cell (-8, 1)
            case 425977 -> 225 ; // Cell (6, -7)
            case -229384 -> 64 ; // Cell (-4, -8)
            case 425986 -> 234 ; // Cell (6, 2)
            case -229375 -> 73 ; // Cell (-4, 1)
            case -98306 -> 102 ; // Cell (-2, -2)
            case -98305 -> 103 ; // Cell (-2, -1)
            case -32770 -> 118 ; // Cell (-1, -2)
            case -32769 -> 119 ; // Cell (-1, -1)
            case 294905 -> 193 ; // Cell (4, -7)
            case -98297 -> 111 ; // Cell (-2, 7)
            case -32761 -> 127 ; // Cell (-1, 7)
            case 491521 -> 249 ; // Cell (7, 1)
            case 294914 -> 202 ; // Cell (4, 2)
            case -360454 -> 34 ; // Cell (-6, -6)
            case 229382 -> 190 ; // Cell (3, 6)
            case -360445 -> 43 ; // Cell (-6, 3)
            case 360451 -> 219 ; // Cell (5, 3)
            case 32766 -> 134 ; // Cell (0, -2)
            case 32767 -> 135 ; // Cell (0, -1)
            case -425992 -> 16 ; // Cell (-7, -8)
            case -491526 -> 2 ; // Cell (-8, -6)
            case 32775 -> 143 ; // Cell (0, 7)
            case 163835 -> 163 ; // Cell (2, -5)
            case 163844 -> 172 ; // Cell (2, 4)
            case -491517 -> 11 ; // Cell (-8, 3)
            case 425979 -> 227 ; // Cell (6, -5)
            case -229382 -> 66 ; // Cell (-4, -6)
            case 491514 -> 242 ; // Cell (7, -6)
            case 425988 -> 236 ; // Cell (6, 4)
            case -229373 -> 75 ; // Cell (-4, 3)
            case -98304 -> 104 ; // Cell (-2, 0)
            case -32768 -> 120 ; // Cell (-1, 0)
            case 491523 -> 251 ; // Cell (7, 3)
            case 294907 -> 195 ; // Cell (4, -5)
            case -360452 -> 36 ; // Cell (-6, -4)
            case 360444 -> 212 ; // Cell (5, -4)
            case -360443 -> 45 ; // Cell (-6, 5)
            case 360453 -> 221 ; // Cell (5, 5)
            case -294908 -> 60 ; // Cell (-5, 4)
            case -163839 -> 89 ; // Cell (-3, 1)
            case 32768 -> 136 ; // Cell (0, 0)
            case 163837 -> 165 ; // Cell (2, -3)
            case -491524 -> 4 ; // Cell (-8, -4)
            case -491515 -> 13 ; // Cell (-8, 5)
            case 425981 -> 229 ; // Cell (6, -3)
            case -229380 -> 68 ; // Cell (-4, -4)
            case -98311 -> 97 ; // Cell (-2, -7)
            case -32775 -> 113 ; // Cell (-1, -7)
            case 425990 -> 238 ; // Cell (6, 6)
            case -425978 -> 30 ; // Cell (-7, 6)
            case -229371 -> 77 ; // Cell (-4, 5)
            case -98302 -> 106 ; // Cell (-2, 2)
            case -32766 -> 122 ; // Cell (-1, 2)
            case 491516 -> 244 ; // Cell (7, -4)
            case 491525 -> 253 ; // Cell (7, 5)
            case 229377 -> 185 ; // Cell (3, 1)
            case -360450 -> 38 ; // Cell (-6, -2)
            case -360449 -> 39 ; // Cell (-6, -1)
            case 360446 -> 214 ; // Cell (5, -2)
            case -163846 -> 82 ; // Cell (-3, -6)
            case 32761 -> 129 ; // Cell (0, -7)
            case -360441 -> 47 ; // Cell (-6, 7)
            case 360447 -> 215 ; // Cell (5, -1)
            case -294906 -> 62 ; // Cell (-5, 6)
            case -163837 -> 91 ; // Cell (-3, 3)
            case 32770 -> 138 ; // Cell (0, 2)
            case 360455 -> 223 ; // Cell (5, 7)
            case -491522 -> 6 ; // Cell (-8, -2)
            case -491521 -> 7 ; // Cell (-8, -1)
            case -491513 -> 15 ; // Cell (-8, 7)
            case 98307 -> 155 ; // Cell (1, 3)
            case -229378 -> 70 ; // Cell (-4, -2)
            case -229377 -> 71 ; // Cell (-4, -1)
            case -98309 -> 99 ; // Cell (-2, -5)
            case -32773 -> 115 ; // Cell (-1, -5)
            case -229369 -> 79 ; // Cell (-4, 7)
            case -98300 -> 108 ; // Cell (-2, 4)
            case -32764 -> 124 ; // Cell (-1, 4)
            case 491518 -> 246 ; // Cell (7, -2)
            case 491519 -> 247 ; // Cell (7, -1)
            case 491527 -> 255 ; // Cell (7, 7)
            case 229370 -> 178 ; // Cell (3, -6)
            case 229379 -> 187 ; // Cell (3, 3)
            case -360448 -> 40 ; // Cell (-6, 0)
            case 360448 -> 216 ; // Cell (5, 0)
            case -163844 -> 84 ; // Cell (-3, -4)
            case 32763 -> 131 ; // Cell (0, -5)
            case 163832 -> 160 ; // Cell (2, -8)
            case -163835 -> 93 ; // Cell (-3, 5)
            case -491520 -> 8 ; // Cell (-8, 0)
            case 98300 -> 148 ; // Cell (1, -4)
            case 425976 -> 224 ; // Cell (6, -8)
            case 98309 -> 157 ; // Cell (1, 5)
            case 425985 -> 233 ; // Cell (6, 1)
            case -425983 -> 25 ; // Cell (-7, 1)
            case -229376 -> 72 ; // Cell (-4, 0)
            case -98307 -> 101 ; // Cell (-2, -3)
            case -32771 -> 117 ; // Cell (-1, -3)
            case 491520 -> 248 ; // Cell (7, 0)
            case 229372 -> 180 ; // Cell (3, -4)
            case -360455 -> 33 ; // Cell (-6, -7)
            case 360441 -> 209 ; // Cell (5, -7)
            case -294920 -> 48 ; // Cell (-5, -8)
            case 229381 -> 189 ; // Cell (3, 5)
            case -360446 -> 42 ; // Cell (-6, 2)
            case 294916 -> 204 ; // Cell (4, 4)
            case -294911 -> 57 ; // Cell (-5, 1)
            case -163842 -> 86 ; // Cell (-3, -2)
            case -163841 -> 87 ; // Cell (-3, -1)
            case 32765 -> 133 ; // Cell (0, -3)
            case 360450 -> 218 ; // Cell (5, 2)
            case -491527 -> 1 ; // Cell (-8, -7)
            case -163833 -> 95 ; // Cell (-3, 7)
            case -491518 -> 10 ; // Cell (-8, 2)
            case 98302 -> 150 ; // Cell (1, -2)
            case 98303 -> 151 ; // Cell (1, -1)
            case 425978 -> 226 ; // Cell (6, -6)
            case -425990 -> 18 ; // Cell (-7, -6)
            case -229383 -> 65 ; // Cell (-4, -7)
            case 98311 -> 159 ; // Cell (1, 7)
            case 491513 -> 241 ; // Cell (7, -7)
            case 163846 -> 174 ; // Cell (2, 6)
            case -425981 -> 27 ; // Cell (-7, 3)
            case -229374 -> 74 ; // Cell (-4, 2)
            case 491522 -> 250 ; // Cell (7, 2)
            case 229374 -> 182 ; // Cell (3, -2)
            case -360453 -> 35 ; // Cell (-6, -5)
            case 229375 -> 183 ; // Cell (3, -1)
            case -294918 -> 50 ; // Cell (-5, -6)
            case 294909 -> 197 ; // Cell (4, -3)
            case 229383 -> 191 ; // Cell (3, 7)
            case -360444 -> 44 ; // Cell (-6, 4)
            case 294918 -> 206 ; // Cell (4, 6)
            case -294909 -> 59 ; // Cell (-5, 3)
            case -163840 -> 88 ; // Cell (-3, 0)
            case 360443 -> 211 ; // Cell (5, -5)
            case 360452 -> 220 ; // Cell (5, 4)
            case -491525 -> 3 ; // Cell (-8, -5)
            case 98304 -> 152 ; // Cell (1, 0)
            case -425988 -> 20 ; // Cell (-7, -4)
            case -229381 -> 67 ; // Cell (-4, -5)
            case -98312 -> 96 ; // Cell (-2, -8)
            case -32776 -> 112 ; // Cell (-1, -8)
            case -425979 -> 29 ; // Cell (-7, 5)
            case -229372 -> 76 ; // Cell (-4, 4)
            case 491515 -> 243 ; // Cell (7, -5)
            case 491524 -> 252 ; // Cell (7, 4)
            case 229376 -> 184 ; // Cell (3, 0)
            case -360451 -> 37 ; // Cell (-6, -3)
            case 360445 -> 213 ; // Cell (5, -3)
            case -294916 -> 52 ; // Cell (-5, -4)
            case -163847 -> 81 ; // Cell (-3, -7)
            case -360442 -> 46 ; // Cell (-6, 6)
            case -294907 -> 61 ; // Cell (-5, 5)
            case -163838 -> 90 ; // Cell (-3, 2)
            case 360454 -> 222 ; // Cell (5, 6)
            case 98297 -> 145 ; // Cell (1, -7)
            case 98306 -> 154 ; // Cell (1, 2)
            case 32772 -> 140 ; // Cell (0, 4)
            case 163841 -> 169 ; // Cell (2, 1)
            case -425986 -> 22 ; // Cell (-7, -2)
            case -425985 -> 23 ; // Cell (-7, -1)
            case -229379 -> 69 ; // Cell (-4, -3)
            case 491517 -> 245 ; // Cell (7, -3)
            case -425977 -> 31 ; // Cell (-7, 7)
            case -32763 -> 125 ; // Cell (-1, 5)
            case 229369 -> 177 ; // Cell (3, -7)
            case 294904 -> 192 ; // Cell (4, -8)
            case -98298 -> 110 ; // Cell (-2, 6)
            case -32762 -> 126 ; // Cell (-1, 6)
            case 229378 -> 186 ; // Cell (3, 2)
            case 294913 -> 201 ; // Cell (4, 1)
            case -294914 -> 54 ; // Cell (-5, -2)
            case -294913 -> 55 ; // Cell (-5, -1)
            case -163845 -> 83 ; // Cell (-3, -5)
            case -294905 -> 63 ; // Cell (-5, 7)
            case -163836 -> 92 ; // Cell (-3, 4)
            case 98299 -> 147 ; // Cell (1, -5)
            case 163834 -> 162 ; // Cell (2, -6)
            case 98308 -> 156 ; // Cell (1, 4)
            case 32774 -> 142 ; // Cell (0, 6)
            case 163843 -> 171 ; // Cell (2, 3)
            case -425984 -> 24 ; // Cell (-7, 0)
            case -32772 -> 116 ; // Cell (-1, -4)
            case 425987 -> 235 ; // Cell (6, 3)
            case 229371 -> 179 ; // Cell (3, -5)
            case -360456 -> 32 ; // Cell (-6, -8)
            case 294906 -> 194 ; // Cell (4, -6)
            case 229380 -> 188 ; // Cell (3, 4)
            case 360440 -> 208 ; // Cell (5, -8)
            case 294915 -> 203 ; // Cell (4, 3)
            case -294912 -> 56 ; // Cell (-5, 0)
            case -163843 -> 85 ; // Cell (-3, -3)
            case 98301 -> 149 ; // Cell (1, -3)
            case 163836 -> 164 ; // Cell (2, -4)
            case -425991 -> 17 ; // Cell (-7, -7)
            case 491512 -> 240 ; // Cell (7, -8)
            case 98310 -> 158 ; // Cell (1, 6)
            case 163845 -> 173 ; // Cell (2, 5)
            case -425982 -> 26 ; // Cell (-7, 2)
            case -491516 -> 12 ; // Cell (-8, 4)
            case 425980 -> 228 ; // Cell (6, -4)
            case 425989 -> 237 ; // Cell (6, 5)
            case -98303 -> 105 ; // Cell (-2, 1)
            case -32767 -> 121 ; // Cell (-1, 1)
            case 229373 -> 181 ; // Cell (3, -3)
            case 360442 -> 210 ; // Cell (5, -6)
            case 294908 -> 196 ; // Cell (4, -4)
            case -294919 -> 49 ; // Cell (-5, -7)
            case 294917 -> 205 ; // Cell (4, 5)
            case -294910 -> 58 ; // Cell (-5, 2)
            case 32760 -> 128 ; // Cell (0, -8)
            case 32769 -> 137 ; // Cell (0, 1)
            case 163838 -> 166 ; // Cell (2, -2)
            case -425989 -> 19 ; // Cell (-7, -5)
            case -491523 -> 5 ; // Cell (-8, -3)
            case 163839 -> 167 ; // Cell (2, -1)
            case 163847 -> 175 ; // Cell (2, 7)
            case -425980 -> 28 ; // Cell (-7, 4)
            case -491514 -> 14 ; // Cell (-8, 6)
            case 425982 -> 230 ; // Cell (6, -2)
            case 425983 -> 231 ; // Cell (6, -1)
            case -98310 -> 98 ; // Cell (-2, -6)
            case -32774 -> 114 ; // Cell (-1, -6)
            case 425991 -> 239 ; // Cell (6, 7)
            case -229370 -> 78 ; // Cell (-4, 6)
            case -98301 -> 107 ; // Cell (-2, 3)
            case -32765 -> 123 ; // Cell (-1, 3)
            case 491526 -> 254 ; // Cell (7, 6)
            case 294910 -> 198 ; // Cell (4, -2)
            case -294917 -> 51 ; // Cell (-5, -5)
            case -163848 -> 80 ; // Cell (-3, -8)
            case 294911 -> 199 ; // Cell (4, -1)
            case 294919 -> 207 ; // Cell (4, 7)
            case 98296 -> 144 ; // Cell (1, -8)
            case 32762 -> 130 ; // Cell (0, -6)
            case 98305 -> 153 ; // Cell (1, 1)
            case 32771 -> 139 ; // Cell (0, 3)
            case 163840 -> 168 ; // Cell (2, 0)
            case -425987 -> 21 ; // Cell (-7, -3)
            case 425984 -> 232 ; // Cell (6, 0)
            case -98308 -> 100 ; // Cell (-2, -4)
            case 229368 -> 176 ; // Cell (3, -8)
            case -98299 -> 109 ; // Cell (-2, 5)
            default -> {
                System.out.println("WARN: Encode relative position not found for cell " + targetLoc );
                yield -1;
            }
        };
    }

    public static MapLocation decodeRelativeLocation(MapLocation senderLoc, int msg){
        return switch(msg & 0b0000_000000000000_000000_11111111){ // Mask relative position
            case 200 -> senderLoc.translate(4, 0);
            case 53 -> senderLoc.translate(-5, -3);
            case 41 -> senderLoc.translate(-6, 1);
            case 217 -> senderLoc.translate(5, 1);
            case 146 -> senderLoc.translate(1, -6);
            case 132 -> senderLoc.translate(0, -4);
            case 161 -> senderLoc.translate(2, -7);
            case 0 -> senderLoc.translate(-8, -8);
            case 94 -> senderLoc.translate(-3, 6);
            case 141 -> senderLoc.translate(0, 5);
            case 170 -> senderLoc.translate(2, 2);
            case 9 -> senderLoc.translate(-8, 1);
            case 225 -> senderLoc.translate(6, -7);
            case 64 -> senderLoc.translate(-4, -8);
            case 234 -> senderLoc.translate(6, 2);
            case 73 -> senderLoc.translate(-4, 1);
            case 102 -> senderLoc.translate(-2, -2);
            case 103 -> senderLoc.translate(-2, -1);
            case 118 -> senderLoc.translate(-1, -2);
            case 119 -> senderLoc.translate(-1, -1);
            case 193 -> senderLoc.translate(4, -7);
            case 111 -> senderLoc.translate(-2, 7);
            case 127 -> senderLoc.translate(-1, 7);
            case 249 -> senderLoc.translate(7, 1);
            case 202 -> senderLoc.translate(4, 2);
            case 34 -> senderLoc.translate(-6, -6);
            case 190 -> senderLoc.translate(3, 6);
            case 43 -> senderLoc.translate(-6, 3);
            case 219 -> senderLoc.translate(5, 3);
            case 134 -> senderLoc.translate(0, -2);
            case 135 -> senderLoc.translate(0, -1);
            case 16 -> senderLoc.translate(-7, -8);
            case 2 -> senderLoc.translate(-8, -6);
            case 143 -> senderLoc.translate(0, 7);
            case 163 -> senderLoc.translate(2, -5);
            case 172 -> senderLoc.translate(2, 4);
            case 11 -> senderLoc.translate(-8, 3);
            case 227 -> senderLoc.translate(6, -5);
            case 66 -> senderLoc.translate(-4, -6);
            case 242 -> senderLoc.translate(7, -6);
            case 236 -> senderLoc.translate(6, 4);
            case 75 -> senderLoc.translate(-4, 3);
            case 104 -> senderLoc.translate(-2, 0);
            case 120 -> senderLoc.translate(-1, 0);
            case 251 -> senderLoc.translate(7, 3);
            case 195 -> senderLoc.translate(4, -5);
            case 36 -> senderLoc.translate(-6, -4);
            case 212 -> senderLoc.translate(5, -4);
            case 45 -> senderLoc.translate(-6, 5);
            case 221 -> senderLoc.translate(5, 5);
            case 60 -> senderLoc.translate(-5, 4);
            case 89 -> senderLoc.translate(-3, 1);
            case 136 -> senderLoc.translate(0, 0);
            case 165 -> senderLoc.translate(2, -3);
            case 4 -> senderLoc.translate(-8, -4);
            case 13 -> senderLoc.translate(-8, 5);
            case 229 -> senderLoc.translate(6, -3);
            case 68 -> senderLoc.translate(-4, -4);
            case 97 -> senderLoc.translate(-2, -7);
            case 113 -> senderLoc.translate(-1, -7);
            case 238 -> senderLoc.translate(6, 6);
            case 30 -> senderLoc.translate(-7, 6);
            case 77 -> senderLoc.translate(-4, 5);
            case 106 -> senderLoc.translate(-2, 2);
            case 122 -> senderLoc.translate(-1, 2);
            case 244 -> senderLoc.translate(7, -4);
            case 253 -> senderLoc.translate(7, 5);
            case 185 -> senderLoc.translate(3, 1);
            case 38 -> senderLoc.translate(-6, -2);
            case 39 -> senderLoc.translate(-6, -1);
            case 214 -> senderLoc.translate(5, -2);
            case 82 -> senderLoc.translate(-3, -6);
            case 129 -> senderLoc.translate(0, -7);
            case 47 -> senderLoc.translate(-6, 7);
            case 215 -> senderLoc.translate(5, -1);
            case 62 -> senderLoc.translate(-5, 6);
            case 91 -> senderLoc.translate(-3, 3);
            case 138 -> senderLoc.translate(0, 2);
            case 223 -> senderLoc.translate(5, 7);
            case 6 -> senderLoc.translate(-8, -2);
            case 7 -> senderLoc.translate(-8, -1);
            case 15 -> senderLoc.translate(-8, 7);
            case 155 -> senderLoc.translate(1, 3);
            case 70 -> senderLoc.translate(-4, -2);
            case 71 -> senderLoc.translate(-4, -1);
            case 99 -> senderLoc.translate(-2, -5);
            case 115 -> senderLoc.translate(-1, -5);
            case 79 -> senderLoc.translate(-4, 7);
            case 108 -> senderLoc.translate(-2, 4);
            case 124 -> senderLoc.translate(-1, 4);
            case 246 -> senderLoc.translate(7, -2);
            case 247 -> senderLoc.translate(7, -1);
            case 255 -> senderLoc.translate(7, 7);
            case 178 -> senderLoc.translate(3, -6);
            case 187 -> senderLoc.translate(3, 3);
            case 40 -> senderLoc.translate(-6, 0);
            case 216 -> senderLoc.translate(5, 0);
            case 84 -> senderLoc.translate(-3, -4);
            case 131 -> senderLoc.translate(0, -5);
            case 160 -> senderLoc.translate(2, -8);
            case 93 -> senderLoc.translate(-3, 5);
            case 8 -> senderLoc.translate(-8, 0);
            case 148 -> senderLoc.translate(1, -4);
            case 224 -> senderLoc.translate(6, -8);
            case 157 -> senderLoc.translate(1, 5);
            case 233 -> senderLoc.translate(6, 1);
            case 25 -> senderLoc.translate(-7, 1);
            case 72 -> senderLoc.translate(-4, 0);
            case 101 -> senderLoc.translate(-2, -3);
            case 117 -> senderLoc.translate(-1, -3);
            case 248 -> senderLoc.translate(7, 0);
            case 180 -> senderLoc.translate(3, -4);
            case 33 -> senderLoc.translate(-6, -7);
            case 209 -> senderLoc.translate(5, -7);
            case 48 -> senderLoc.translate(-5, -8);
            case 189 -> senderLoc.translate(3, 5);
            case 42 -> senderLoc.translate(-6, 2);
            case 204 -> senderLoc.translate(4, 4);
            case 57 -> senderLoc.translate(-5, 1);
            case 86 -> senderLoc.translate(-3, -2);
            case 87 -> senderLoc.translate(-3, -1);
            case 133 -> senderLoc.translate(0, -3);
            case 218 -> senderLoc.translate(5, 2);
            case 1 -> senderLoc.translate(-8, -7);
            case 95 -> senderLoc.translate(-3, 7);
            case 10 -> senderLoc.translate(-8, 2);
            case 150 -> senderLoc.translate(1, -2);
            case 151 -> senderLoc.translate(1, -1);
            case 226 -> senderLoc.translate(6, -6);
            case 18 -> senderLoc.translate(-7, -6);
            case 65 -> senderLoc.translate(-4, -7);
            case 159 -> senderLoc.translate(1, 7);
            case 241 -> senderLoc.translate(7, -7);
            case 174 -> senderLoc.translate(2, 6);
            case 27 -> senderLoc.translate(-7, 3);
            case 74 -> senderLoc.translate(-4, 2);
            case 250 -> senderLoc.translate(7, 2);
            case 182 -> senderLoc.translate(3, -2);
            case 35 -> senderLoc.translate(-6, -5);
            case 183 -> senderLoc.translate(3, -1);
            case 50 -> senderLoc.translate(-5, -6);
            case 197 -> senderLoc.translate(4, -3);
            case 191 -> senderLoc.translate(3, 7);
            case 44 -> senderLoc.translate(-6, 4);
            case 206 -> senderLoc.translate(4, 6);
            case 59 -> senderLoc.translate(-5, 3);
            case 88 -> senderLoc.translate(-3, 0);
            case 211 -> senderLoc.translate(5, -5);
            case 220 -> senderLoc.translate(5, 4);
            case 3 -> senderLoc.translate(-8, -5);
            case 152 -> senderLoc.translate(1, 0);
            case 20 -> senderLoc.translate(-7, -4);
            case 67 -> senderLoc.translate(-4, -5);
            case 96 -> senderLoc.translate(-2, -8);
            case 112 -> senderLoc.translate(-1, -8);
            case 29 -> senderLoc.translate(-7, 5);
            case 76 -> senderLoc.translate(-4, 4);
            case 243 -> senderLoc.translate(7, -5);
            case 252 -> senderLoc.translate(7, 4);
            case 184 -> senderLoc.translate(3, 0);
            case 37 -> senderLoc.translate(-6, -3);
            case 213 -> senderLoc.translate(5, -3);
            case 52 -> senderLoc.translate(-5, -4);
            case 81 -> senderLoc.translate(-3, -7);
            case 46 -> senderLoc.translate(-6, 6);
            case 61 -> senderLoc.translate(-5, 5);
            case 90 -> senderLoc.translate(-3, 2);
            case 222 -> senderLoc.translate(5, 6);
            case 145 -> senderLoc.translate(1, -7);
            case 154 -> senderLoc.translate(1, 2);
            case 140 -> senderLoc.translate(0, 4);
            case 169 -> senderLoc.translate(2, 1);
            case 22 -> senderLoc.translate(-7, -2);
            case 23 -> senderLoc.translate(-7, -1);
            case 69 -> senderLoc.translate(-4, -3);
            case 245 -> senderLoc.translate(7, -3);
            case 31 -> senderLoc.translate(-7, 7);
            case 125 -> senderLoc.translate(-1, 5);
            case 177 -> senderLoc.translate(3, -7);
            case 192 -> senderLoc.translate(4, -8);
            case 110 -> senderLoc.translate(-2, 6);
            case 126 -> senderLoc.translate(-1, 6);
            case 186 -> senderLoc.translate(3, 2);
            case 201 -> senderLoc.translate(4, 1);
            case 54 -> senderLoc.translate(-5, -2);
            case 55 -> senderLoc.translate(-5, -1);
            case 83 -> senderLoc.translate(-3, -5);
            case 63 -> senderLoc.translate(-5, 7);
            case 92 -> senderLoc.translate(-3, 4);
            case 147 -> senderLoc.translate(1, -5);
            case 162 -> senderLoc.translate(2, -6);
            case 156 -> senderLoc.translate(1, 4);
            case 142 -> senderLoc.translate(0, 6);
            case 171 -> senderLoc.translate(2, 3);
            case 24 -> senderLoc.translate(-7, 0);
            case 116 -> senderLoc.translate(-1, -4);
            case 235 -> senderLoc.translate(6, 3);
            case 179 -> senderLoc.translate(3, -5);
            case 32 -> senderLoc.translate(-6, -8);
            case 194 -> senderLoc.translate(4, -6);
            case 188 -> senderLoc.translate(3, 4);
            case 208 -> senderLoc.translate(5, -8);
            case 203 -> senderLoc.translate(4, 3);
            case 56 -> senderLoc.translate(-5, 0);
            case 85 -> senderLoc.translate(-3, -3);
            case 149 -> senderLoc.translate(1, -3);
            case 164 -> senderLoc.translate(2, -4);
            case 17 -> senderLoc.translate(-7, -7);
            case 240 -> senderLoc.translate(7, -8);
            case 158 -> senderLoc.translate(1, 6);
            case 173 -> senderLoc.translate(2, 5);
            case 26 -> senderLoc.translate(-7, 2);
            case 12 -> senderLoc.translate(-8, 4);
            case 228 -> senderLoc.translate(6, -4);
            case 237 -> senderLoc.translate(6, 5);
            case 105 -> senderLoc.translate(-2, 1);
            case 121 -> senderLoc.translate(-1, 1);
            case 181 -> senderLoc.translate(3, -3);
            case 210 -> senderLoc.translate(5, -6);
            case 196 -> senderLoc.translate(4, -4);
            case 49 -> senderLoc.translate(-5, -7);
            case 205 -> senderLoc.translate(4, 5);
            case 58 -> senderLoc.translate(-5, 2);
            case 128 -> senderLoc.translate(0, -8);
            case 137 -> senderLoc.translate(0, 1);
            case 166 -> senderLoc.translate(2, -2);
            case 19 -> senderLoc.translate(-7, -5);
            case 5 -> senderLoc.translate(-8, -3);
            case 167 -> senderLoc.translate(2, -1);
            case 175 -> senderLoc.translate(2, 7);
            case 28 -> senderLoc.translate(-7, 4);
            case 14 -> senderLoc.translate(-8, 6);
            case 230 -> senderLoc.translate(6, -2);
            case 231 -> senderLoc.translate(6, -1);
            case 98 -> senderLoc.translate(-2, -6);
            case 114 -> senderLoc.translate(-1, -6);
            case 239 -> senderLoc.translate(6, 7);
            case 78 -> senderLoc.translate(-4, 6);
            case 107 -> senderLoc.translate(-2, 3);
            case 123 -> senderLoc.translate(-1, 3);
            case 254 -> senderLoc.translate(7, 6);
            case 198 -> senderLoc.translate(4, -2);
            case 51 -> senderLoc.translate(-5, -5);
            case 80 -> senderLoc.translate(-3, -8);
            case 199 -> senderLoc.translate(4, -1);
            case 207 -> senderLoc.translate(4, 7);
            case 144 -> senderLoc.translate(1, -8);
            case 130 -> senderLoc.translate(0, -6);
            case 153 -> senderLoc.translate(1, 1);
            case 139 -> senderLoc.translate(0, 3);
            case 168 -> senderLoc.translate(2, 0);
            case 21 -> senderLoc.translate(-7, -3);
            case 232 -> senderLoc.translate(6, 0);
            case 100 -> senderLoc.translate(-2, -4);
            case 176 -> senderLoc.translate(3, -8);
            case 109 -> senderLoc.translate(-2, 5);
            default -> {
                System.out.println("WARN: Decode relative position not found for cell " + msg );
                yield null;
            }
        };
    }
}