// #########################################################
// !!!!!!!!!! This file is generated by jinja.py !!!!!!!!!!!
// !!!! Dont edit it manually, check in template folder !!!!
// #########################################################

//  Destination: States/ThrowToWalls.java

package current.States;

import battlecode.common.*;
import current.Utils.BugNavLmx;

import static current.States.Code.*;

public class ThrowToWalls extends State {

    public ThrowToWalls(){
        this.name = "ThrowToWalls";
    }

    @Override
    public Result run() throws GameActionException {
        if(rc.getCarrying() == null){
            return new Result(OK, "");
        }

        if(!rc.isActionReady() && !rc.canTurn()){
            return new Result(OK, "Not action ready");
        }

        if(rc.getRoundNum() - roundRatnap <= 5){
            return new Result(OK, "Too soon to throw");
        }

        int score = checkDirectionThrow(rc.getDirection());
        Direction bestDir = rc.getDirection();
        // System.out.println("CheckDirectionThrow " + rc.getDirection() + ":" + score);

        int s = checkDirectionThrow(rc.getDirection().rotateRight());
        // System.out.println("CheckDirectionThrow " + rc.getDirection().rotateRight() + ":" + s);
        if(s < score){
            score = s;
            bestDir = rc.getDirection().rotateRight();
        }

        s = checkDirectionThrow(rc.getDirection().rotateLeft());
        // System.out.println("CheckDirectionThrow " + rc.getDirection().rotateLeft() + ":" + s);
        if(s < score){
            score = s;
            bestDir = rc.getDirection().rotateLeft();
        }

        Direction d = rc.getDirection().rotateRight();
        for(int i = 0; i < 5; i++){
            d = d.rotateRight();
            s = checkDirectionThrow(d);
            // System.out.println("CheckDirectionThrow " + d + ":" + s);
            if(s < score){
                score = s;
                bestDir = d;
            }
        }

        if(score < 10){
            return playThrow(bestDir);
        }

        return new Result(OK, "Can't throw to walls s=" + score);
    };

    public static Result playThrow(Direction dir) throws GameActionException {
        // Turn in correct direction if needed
        if(rc.getDirection() != dir){
            if(rc.canTurn()){
                rc.turn(dir);
            }else{
                return new Result(ERR, "Need turn to throw to " + dir);
            }
        }

        // Update score
        int score = checkDirectionThrow(rc.getDirection());
        if(score >= 10){
            return new Result(OK, "Can't throw to walls s=" + score);
        }

        // Moving back for 1
        if(score == 1 && rc.canMove(dir.opposite())){
            lastLocation = myLoc;
            lastDirection = dir.opposite();
            rc.move(dir.opposite());
            myLoc = myLoc.add(dir.opposite());
        }

        // Moving front to make more damage
        if(score > 1 && rc.canMove(dir)){
            lastLocation = myLoc;
            lastDirection = dir;
            rc.move(dir);
            myLoc = myLoc.add(dir);
        }

        // can't throw ?
        if(!rc.canThrowRat()){
            return new Result(ERR, "Can't throw ???!!!");
        }

        // Add enemies rats back to the list of enemies on the map (especialy the one we are throwing)
        MapLocation enemyLoc = rc.getLocation().add(dir);
        if(score >= 2){enemyLoc = enemyLoc.add(dir);}
        if(score >= 3){enemyLoc = enemyLoc.add(dir);}
        enemiesRats.add(enemyLoc, rc.getCarrying().getID());

        rc.throwRat();
        return new Result(OK, "Enemy throw !");
    }

    public static int checkDirectionThrow(Direction dir) throws GameActionException {
        // 10: not possible (Ally)
        // 11: not possible (too narrow)
        //  0: Without moving
        //  1: Move backward
        //  2: Move direction
        //  3: Move + 2 dist in direction 
        // 12: Too far
        // 13: Out of the map
        MapLocation loc = myLoc.add(dir);
        char[] mapCosts = BugNavLmx.mapCosts;
        int xy = myLoc.x + (myLoc.y<<7) + 129;
        int SCORE_CELL_WALL = BugNavLmx.SCORE_CELL_WALL;

        switch(dir){
            case Direction.NORTH:
                if(rc.canSenseLocation(loc)){
                    if(rc.canSenseRobotAtLocation(loc)){
                        return 10;
                    }

                    if(!rc.senseMapInfo(loc).isPassable()){
                        if(rc.canMove(Direction.SOUTH)){
                            return 1;
                        }else{
                            return 11;
                        }
                    }

                    loc = loc.add(Direction.NORTH);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 15;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 0;
                    }

                    loc = loc.add(Direction.NORTH);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 2;
                    }

                    loc = loc.add(Direction.NORTH);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 3;
                    }

                    return 17;
                }else{
                    if(mapCosts[xy + 128] >= SCORE_CELL_WALL){
                        if(rc.canMove(Direction.SOUTH)){
                            return 1;
                        }else{
                            return 17;
                        }
                    }

                    if(mapCosts[xy + 256] >= SCORE_CELL_WALL){
                        return 0;
                    }

                    if(mapCosts[xy + 384] >= SCORE_CELL_WALL){
                        return 2;
                    }

                    if(mapCosts[xy + 512] >= SCORE_CELL_WALL){
                        return 3;
                    }
                    return 12;
                }
            case Direction.NORTHEAST:
                if(rc.canSenseLocation(loc)){
                    if(rc.canSenseRobotAtLocation(loc)){
                        return 10;
                    }

                    if(!rc.senseMapInfo(loc).isPassable()){
                        if(rc.canMove(Direction.SOUTHWEST)){
                            return 1;
                        }else{
                            return 11;
                        }
                    }

                    loc = loc.add(Direction.NORTHEAST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 15;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 0;
                    }

                    loc = loc.add(Direction.NORTHEAST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 2;
                    }

                    loc = loc.add(Direction.NORTHEAST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 3;
                    }

                    return 17;
                }else{
                    if(mapCosts[xy + 129] >= SCORE_CELL_WALL){
                        if(rc.canMove(Direction.SOUTHWEST)){
                            return 1;
                        }else{
                            return 17;
                        }
                    }

                    if(mapCosts[xy + 258] >= SCORE_CELL_WALL){
                        return 0;
                    }

                    if(mapCosts[xy + 387] >= SCORE_CELL_WALL){
                        return 2;
                    }

                    if(mapCosts[xy + 516] >= SCORE_CELL_WALL){
                        return 3;
                    }
                    return 12;
                }
            case Direction.EAST:
                if(rc.canSenseLocation(loc)){
                    if(rc.canSenseRobotAtLocation(loc)){
                        return 10;
                    }

                    if(!rc.senseMapInfo(loc).isPassable()){
                        if(rc.canMove(Direction.WEST)){
                            return 1;
                        }else{
                            return 11;
                        }
                    }

                    loc = loc.add(Direction.EAST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 15;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 0;
                    }

                    loc = loc.add(Direction.EAST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 2;
                    }

                    loc = loc.add(Direction.EAST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 3;
                    }

                    return 17;
                }else{
                    if(mapCosts[xy + 1] >= SCORE_CELL_WALL){
                        if(rc.canMove(Direction.WEST)){
                            return 1;
                        }else{
                            return 17;
                        }
                    }

                    if(mapCosts[xy + 2] >= SCORE_CELL_WALL){
                        return 0;
                    }

                    if(mapCosts[xy + 3] >= SCORE_CELL_WALL){
                        return 2;
                    }

                    if(mapCosts[xy + 4] >= SCORE_CELL_WALL){
                        return 3;
                    }
                    return 12;
                }
            case Direction.SOUTHEAST:
                if(rc.canSenseLocation(loc)){
                    if(rc.canSenseRobotAtLocation(loc)){
                        return 10;
                    }

                    if(!rc.senseMapInfo(loc).isPassable()){
                        if(rc.canMove(Direction.NORTHWEST)){
                            return 1;
                        }else{
                            return 11;
                        }
                    }

                    loc = loc.add(Direction.SOUTHEAST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 15;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 0;
                    }

                    loc = loc.add(Direction.SOUTHEAST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 2;
                    }

                    loc = loc.add(Direction.SOUTHEAST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 3;
                    }

                    return 17;
                }else{
                    if(mapCosts[xy - 127] >= SCORE_CELL_WALL){
                        if(rc.canMove(Direction.NORTHWEST)){
                            return 1;
                        }else{
                            return 17;
                        }
                    }

                    if(mapCosts[xy - 254] >= SCORE_CELL_WALL){
                        return 0;
                    }

                    if(mapCosts[xy - 381] >= SCORE_CELL_WALL){
                        return 2;
                    }

                    if(mapCosts[xy - 508] >= SCORE_CELL_WALL){
                        return 3;
                    }
                    return 12;
                }
            case Direction.SOUTH:
                if(rc.canSenseLocation(loc)){
                    if(rc.canSenseRobotAtLocation(loc)){
                        return 10;
                    }

                    if(!rc.senseMapInfo(loc).isPassable()){
                        if(rc.canMove(Direction.NORTH)){
                            return 1;
                        }else{
                            return 11;
                        }
                    }

                    loc = loc.add(Direction.SOUTH);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 15;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 0;
                    }

                    loc = loc.add(Direction.SOUTH);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 2;
                    }

                    loc = loc.add(Direction.SOUTH);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 3;
                    }

                    return 17;
                }else{
                    if(mapCosts[xy - 128] >= SCORE_CELL_WALL){
                        if(rc.canMove(Direction.NORTH)){
                            return 1;
                        }else{
                            return 17;
                        }
                    }

                    if(mapCosts[xy - 256] >= SCORE_CELL_WALL){
                        return 0;
                    }

                    if(mapCosts[xy - 384] >= SCORE_CELL_WALL){
                        return 2;
                    }

                    if(mapCosts[xy - 512] >= SCORE_CELL_WALL){
                        return 3;
                    }
                    return 12;
                }
            case Direction.SOUTHWEST:
                if(rc.canSenseLocation(loc)){
                    if(rc.canSenseRobotAtLocation(loc)){
                        return 10;
                    }

                    if(!rc.senseMapInfo(loc).isPassable()){
                        if(rc.canMove(Direction.NORTHEAST)){
                            return 1;
                        }else{
                            return 11;
                        }
                    }

                    loc = loc.add(Direction.SOUTHWEST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 15;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 0;
                    }

                    loc = loc.add(Direction.SOUTHWEST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 2;
                    }

                    loc = loc.add(Direction.SOUTHWEST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 3;
                    }

                    return 17;
                }else{
                    if(mapCosts[xy - 129] >= SCORE_CELL_WALL){
                        if(rc.canMove(Direction.NORTHEAST)){
                            return 1;
                        }else{
                            return 17;
                        }
                    }

                    if(mapCosts[xy - 258] >= SCORE_CELL_WALL){
                        return 0;
                    }

                    if(mapCosts[xy - 387] >= SCORE_CELL_WALL){
                        return 2;
                    }

                    if(mapCosts[xy - 516] >= SCORE_CELL_WALL){
                        return 3;
                    }
                    return 12;
                }
            case Direction.WEST:
                if(rc.canSenseLocation(loc)){
                    if(rc.canSenseRobotAtLocation(loc)){
                        return 10;
                    }

                    if(!rc.senseMapInfo(loc).isPassable()){
                        if(rc.canMove(Direction.EAST)){
                            return 1;
                        }else{
                            return 11;
                        }
                    }

                    loc = loc.add(Direction.WEST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 15;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 0;
                    }

                    loc = loc.add(Direction.WEST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 2;
                    }

                    loc = loc.add(Direction.WEST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 3;
                    }

                    return 17;
                }else{
                    if(mapCosts[xy - 1] >= SCORE_CELL_WALL){
                        if(rc.canMove(Direction.EAST)){
                            return 1;
                        }else{
                            return 17;
                        }
                    }

                    if(mapCosts[xy - 2] >= SCORE_CELL_WALL){
                        return 0;
                    }

                    if(mapCosts[xy - 3] >= SCORE_CELL_WALL){
                        return 2;
                    }

                    if(mapCosts[xy - 4] >= SCORE_CELL_WALL){
                        return 3;
                    }
                    return 12;
                }
            case Direction.NORTHWEST:
                if(rc.canSenseLocation(loc)){
                    if(rc.canSenseRobotAtLocation(loc)){
                        return 10;
                    }

                    if(!rc.senseMapInfo(loc).isPassable()){
                        if(rc.canMove(Direction.SOUTHEAST)){
                            return 1;
                        }else{
                            return 11;
                        }
                    }

                    loc = loc.add(Direction.NORTHWEST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 15;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 0;
                    }

                    loc = loc.add(Direction.NORTHWEST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 2;
                    }

                    loc = loc.add(Direction.NORTHWEST);
                    if(!rc.canSenseLocation(loc)){return 13;}
                    if(rc.canSenseRobotAtLocation(loc)){return 17;} // Ally
                    if(!rc.senseMapInfo(loc).isPassable()){
                        return 3;
                    }

                    return 17;
                }else{
                    if(mapCosts[xy + 127] >= SCORE_CELL_WALL){
                        if(rc.canMove(Direction.SOUTHEAST)){
                            return 1;
                        }else{
                            return 17;
                        }
                    }

                    if(mapCosts[xy + 254] >= SCORE_CELL_WALL){
                        return 0;
                    }

                    if(mapCosts[xy + 381] >= SCORE_CELL_WALL){
                        return 2;
                    }

                    if(mapCosts[xy + 508] >= SCORE_CELL_WALL){
                        return 3;
                    }
                    return 12;
                }
            default:
                System.out.println("CheckDirectionThrow called with center.");
                return 10;
        }
    }

}